details:
  namespace: student36-bookinfo-prd
  image: ghcr.io/xsolagul/bookinfo-details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.opsta.net
  path: "/student36/details(/|$)(.*)"
  serviceType: ClusterIP