apiVersion: v1
description: Bookinfo Details Service Helm Chart
name: bookinfo-details
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo.dev.opsta.net/student36/details
maintainers:
  - name: student36
    email: devop036@mail.kmutt.ac.th
sources:
  - https://github.com/xsolagul/bookinfo-details